In [1]:
import numpy as np

### Arrays

In [2]:
A=np.zeros((3,4,3))
A

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [3]:
B=np.ones((4,5))
B

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
C=np.eye(3,5)
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [66]:
A=np.array(list([1,2,3,4,5]))
type(A)

numpy.ndarray

In [67]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
A.shape

(3, 3)

In [7]:
A.size

9

In [8]:
A.diagonal()

array([1, 5, 9])

In [9]:
np.linalg.inv(A)

LinAlgError: ignored

In [10]:
np.linalg.det(A)

0.0

In [11]:
A=np.array([[1,2,3],[4,-2,-3],[7,8,-9]])
A

array([[ 1,  2,  3],
       [ 4, -2, -3],
       [ 7,  8, -9]])

In [12]:
np.linalg.det(A)

209.99999999999994

In [13]:
np.linalg.inv(A)

array([[ 0.2       ,  0.2       ,  0.        ],
       [ 0.07142857, -0.14285714,  0.07142857],
       [ 0.21904762,  0.02857143, -0.04761905]])

In [14]:
np.linalg.eigvals(A)

array([ 3.82566671+0.j        , -6.91283335+2.66554457j,
       -6.91283335-2.66554457j])

In [15]:
np.linalg.eig(A)

(array([ 3.82566671+0.j        , -6.91283335+2.66554457j,
        -6.91283335-2.66554457j]),
 array([[ 0.78140269+0.j        ,  0.30806784+0.20860998j,
          0.30806784-0.20860998j],
        [ 0.23986073+0.j        , -0.45139939-0.41476374j,
         -0.45139939+0.41476374j],
        [ 0.57608737+0.j        , -0.69698329+0.j        ,
         -0.69698329-0.j        ]]))

In [16]:
A.dot(np.linalg.inv(A))

array([[ 1.00000000e+00, -1.04083409e-17,  0.00000000e+00],
       [ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16, -7.97972799e-17,  1.00000000e+00]])

In [17]:
A.argmin()

8

In [18]:
A=A.reshape((1,9))
A

array([[ 1,  2,  3,  4, -2, -3,  7,  8, -9]])

In [19]:
A.argmax()

7

In [20]:
A.max()

8

In [21]:
A.argmin()

8

In [22]:
A.min()

-9

In [23]:
np.invert(A)

array([[-2, -3, -4, -5,  1,  2, -8, -9,  8]])

In [24]:
A

array([[ 1,  2,  3,  4, -2, -3,  7,  8, -9]])

In [25]:
np.random.normal(0.1,0.4,size=(3,4))

array([[-0.00112431,  0.27319031, -0.90020748,  0.2772724 ],
       [ 0.60220224,  0.01478932, -0.13499507,  0.04802485],
       [-0.41097582, -0.18442488,  0.44428739,  0.11081615]])

In [26]:
E=np.random.random((3,4))
E

array([[0.67165868, 0.38642624, 0.38071616, 0.27855508],
       [0.47303686, 0.02792718, 0.66795717, 0.29043314],
       [0.22630023, 0.9252943 , 0.85663481, 0.89911037]])

In [27]:
F=np.random.randint(10,size=(3,7))
F

array([[5, 6, 7, 6, 3, 1, 2],
       [1, 8, 3, 0, 7, 1, 4],
       [9, 4, 6, 2, 6, 2, 9]])

In [28]:
G=np.sqrt(F)
G

array([[2.23606798, 2.44948974, 2.64575131, 2.44948974, 1.73205081,
        1.        , 1.41421356],
       [1.        , 2.82842712, 1.73205081, 0.        , 2.64575131,
        1.        , 2.        ],
       [3.        , 2.        , 2.44948974, 1.41421356, 2.44948974,
        1.41421356, 3.        ]])

In [29]:
F=np.array([[1,2,3],[4,5,6],[7,8,9]])
G=np.log(F)
G

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [30]:
np.exp(F)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [31]:
H=np.array([i for i in range(12,50,5)])
H

array([12, 17, 22, 27, 32, 37, 42, 47])

In [32]:
H= np.array([i if (i%2==0 and i%3==2) else  10-i     for i  in range(12,50,5)])
H

array([ -2,  -7, -12, -17,  32, -27, -32, -37])

In [33]:
def function(i):
    if (i%2==0 and i%3==2):
        return i
    else:
        return 10-i

In [34]:
H=np.array([ function(i)  for i  in range(12,50,5) ])
H

array([ -2,  -7, -12, -17,  32, -27, -32, -37])

In [35]:
H.size

8

In [36]:
H=H.reshape((2,4))

In [37]:
H

array([[ -2,  -7, -12, -17],
       [ 32, -27, -32, -37]])

In [38]:
np.sum(H,axis=1)

array([-38, -64])

In [39]:
np.sum(H,axis=0)

array([ 30, -34, -44, -54])

In [40]:
H.sum(axis=1)

array([-38, -64])

In [41]:
np.sum(H)

-102

In [42]:
A=np.random.random((5,8))
B=np.random.random((5,8))

In [43]:
A

array([[0.10738186, 0.84931939, 0.42639098, 0.03266724, 0.47252976,
        0.83078675, 0.16126431, 0.2571901 ],
       [0.19956646, 0.39287083, 0.70148415, 0.77912766, 0.72625028,
        0.56631607, 0.18958176, 0.07033865],
       [0.97583063, 0.46159192, 0.2227542 , 0.35268458, 0.50131928,
        0.02450848, 0.96006423, 0.51510049],
       [0.04386387, 0.6627082 , 0.80315216, 0.66283618, 0.4853275 ,
        0.04074959, 0.38553529, 0.07132161],
       [0.09510168, 0.37532986, 0.98285808, 0.9786086 , 0.0844127 ,
        0.41892134, 0.28394073, 0.75994044]])

In [44]:
B

array([[0.11907121, 0.44382202, 0.61135561, 0.4611416 , 0.69662307,
        0.88754532, 0.4763395 , 0.14373274],
       [0.47456605, 0.95326822, 0.65869577, 0.2729163 , 0.11736177,
        0.11575928, 0.87077955, 0.56213836],
       [0.66010244, 0.3186194 , 0.20519263, 0.85069138, 0.10342604,
        0.15925709, 0.90279493, 0.31368705],
       [0.36404364, 0.38478282, 0.36384612, 0.5014036 , 0.78572835,
        0.92850838, 0.36613247, 0.98830155],
       [0.27633259, 0.9755439 , 0.04228812, 0.64619176, 0.19634108,
        0.76993056, 0.50089919, 0.42846387]])

In [45]:
A+B

array([[0.22645306, 1.29314141, 1.03774659, 0.49380884, 1.16915284,
        1.71833207, 0.63760381, 0.40092283],
       [0.67413251, 1.34613905, 1.36017992, 1.05204396, 0.84361206,
        0.68207534, 1.06036131, 0.63247701],
       [1.63593307, 0.78021132, 0.42794683, 1.20337597, 0.60474532,
        0.18376556, 1.86285916, 0.82878754],
       [0.40790751, 1.04749102, 1.16699828, 1.16423978, 1.27105585,
        0.96925797, 0.75166775, 1.05962316],
       [0.37143427, 1.35087375, 1.0251462 , 1.62480036, 0.28075378,
        1.1888519 , 0.78483992, 1.18840431]])

In [46]:
A-B

array([[-0.01168935,  0.40549737, -0.18496464, -0.42847436, -0.22409331,
        -0.05675857, -0.31507519,  0.11345736],
       [-0.27499959, -0.56039739,  0.04278837,  0.50621136,  0.60888851,
         0.45055679, -0.6811978 , -0.49179971],
       [ 0.31572819,  0.14297253,  0.01756157, -0.4980068 ,  0.39789324,
        -0.13474861,  0.05726931,  0.20141344],
       [-0.32017977,  0.27792537,  0.43930605,  0.16143258, -0.30040085,
        -0.8877588 ,  0.01940282, -0.91697993],
       [-0.18123091, -0.60021404,  0.94056995,  0.33241684, -0.11192838,
        -0.35100922, -0.21695846,  0.33147658]])

In [47]:
A.T

array([[0.10738186, 0.19956646, 0.97583063, 0.04386387, 0.09510168],
       [0.84931939, 0.39287083, 0.46159192, 0.6627082 , 0.37532986],
       [0.42639098, 0.70148415, 0.2227542 , 0.80315216, 0.98285808],
       [0.03266724, 0.77912766, 0.35268458, 0.66283618, 0.9786086 ],
       [0.47252976, 0.72625028, 0.50131928, 0.4853275 , 0.0844127 ],
       [0.83078675, 0.56631607, 0.02450848, 0.04074959, 0.41892134],
       [0.16126431, 0.18958176, 0.96006423, 0.38553529, 0.28394073],
       [0.2571901 , 0.07033865, 0.51510049, 0.07132161, 0.75994044]])

In [48]:
A.T.dot(B)

array([[0.79388979, 0.65847129, 0.41731671, 1.01756131, 0.2522899 ,
        0.38776553, 1.16959989, 0.51782204],
       [0.93724117, 1.51967954, 1.12972959, 1.46636896, 1.27990542,
        1.77710772, 1.59403251, 1.30348899],
       [1.0946902 , 2.19677842, 1.10223571, 1.61538633, 1.22643465,
        1.99758579, 1.80141918, 1.7403683 ],
       [1.11816797, 2.07931185, 0.88810157, 1.49244386, 0.86362358,
        1.54426205, 1.74528108, 1.62768593],
       [0.93184687, 1.33085445, 1.05028292, 1.14046841, 0.86416788,
        1.098923  , 1.5300534 , 1.14924621],
       [0.51445151, 1.34073734, 0.91850708, 0.84965188, 0.76201347,
        1.16719706, 1.13575623, 0.66521277],
       [0.96172549, 0.98353401, 0.57274749, 1.31961295, 0.59256097,
        0.89455965, 1.39202426, 0.93359332],
       [0.63998385, 1.11411783, 0.36734775, 1.10281733, 0.44594137,
        0.96976771, 1.05555608, 0.63418132]])

In [49]:
A*B

array([[0.01278609, 0.37694665, 0.26067652, 0.01506422, 0.32917514,
        0.7373609 , 0.07681656, 0.03696664],
       [0.09470747, 0.37451128, 0.46206464, 0.21263664, 0.08523402,
        0.06555634, 0.16508392, 0.03954005],
       [0.64414818, 0.14707214, 0.04570752, 0.30002574, 0.05184947,
        0.00390315, 0.86674112, 0.16158035],
       [0.01596836, 0.25499873, 0.2922238 , 0.33234845, 0.38133558,
        0.03783633, 0.14115699, 0.07048726],
       [0.02627969, 0.36615075, 0.04156323, 0.63236881, 0.01657368,
        0.32254034, 0.14222568, 0.32560702]])

In [50]:
D=np.random.random((5,8))
D

array([[0.44099768, 0.88771631, 0.46180284, 0.33595133, 0.04996738,
        0.71845467, 0.01403111, 0.48310059],
       [0.62901714, 0.04727887, 0.95908308, 0.53370166, 0.49061463,
        0.49308542, 0.61425535, 0.24304294],
       [0.5923228 , 0.60979814, 0.57319505, 0.02281875, 0.33780291,
        0.38231867, 0.40160924, 0.59124012],
       [0.60288767, 0.41271191, 0.75130041, 0.0348518 , 0.56367462,
        0.79648391, 0.00135118, 0.13404054],
       [0.27018412, 0.13228253, 0.72313327, 0.70329348, 0.12213822,
        0.8890736 , 0.22080837, 0.19150993]])

In [51]:
C=np.array(D*100,dtype=int)
C

array([[44, 88, 46, 33,  4, 71,  1, 48],
       [62,  4, 95, 53, 49, 49, 61, 24],
       [59, 60, 57,  2, 33, 38, 40, 59],
       [60, 41, 75,  3, 56, 79,  0, 13],
       [27, 13, 72, 70, 12, 88, 22, 19]])

In [52]:
D=np.linspace(1,120,5)
D

array([  1.  ,  30.75,  60.5 ,  90.25, 120.  ])

In [53]:
F=np.array([i for i in range(120)])
F

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [54]:
F[F%7==1]

array([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
        92,  99, 106, 113])

In [55]:
F[((F%3==0) & (F%4==2)) | (F%5==1)]

array([  1,   6,  11,  16,  18,  21,  26,  30,  31,  36,  41,  42,  46,
        51,  54,  56,  61,  66,  71,  76,  78,  81,  86,  90,  91,  96,
       101, 102, 106, 111, 114, 116])

In [56]:
a = np.array([1, 3, 0], float) 
    
np.where(a != 0, 1 / a, a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([1.        , 0.33333333, 0.        ])

In [57]:
g=np.random.random((3,5))*100
g

array([[27.20848423,  4.31478364, 13.72736843, 30.17416081, 83.7035231 ],
       [96.00317474, 72.55902806, 55.38843271, 72.32059774, 38.89234965],
       [ 0.34696495, 69.81726138, 50.44230549, 55.64681499,  3.58593394]])

In [58]:
g.max()

96.00317474105427

In [59]:
g.argmax()

5

In [60]:
g.mean()

44.94207892381982

In [61]:
g.argsort(axis=0)

array([[2, 0, 0, 0, 2],
       [0, 2, 2, 2, 1],
       [1, 1, 1, 1, 0]])

In [62]:
g.argsort(axis=1)

array([[1, 2, 0, 3, 4],
       [4, 2, 3, 1, 0],
       [0, 4, 2, 3, 1]])

In [63]:
g.flatten()

array([27.20848423,  4.31478364, 13.72736843, 30.17416081, 83.7035231 ,
       96.00317474, 72.55902806, 55.38843271, 72.32059774, 38.89234965,
        0.34696495, 69.81726138, 50.44230549, 55.64681499,  3.58593394])

In [64]:
g.repeat(3)

array([27.20848423, 27.20848423, 27.20848423,  4.31478364,  4.31478364,
        4.31478364, 13.72736843, 13.72736843, 13.72736843, 30.17416081,
       30.17416081, 30.17416081, 83.7035231 , 83.7035231 , 83.7035231 ,
       96.00317474, 96.00317474, 96.00317474, 72.55902806, 72.55902806,
       72.55902806, 55.38843271, 55.38843271, 55.38843271, 72.32059774,
       72.32059774, 72.32059774, 38.89234965, 38.89234965, 38.89234965,
        0.34696495,  0.34696495,  0.34696495, 69.81726138, 69.81726138,
       69.81726138, 50.44230549, 50.44230549, 50.44230549, 55.64681499,
       55.64681499, 55.64681499,  3.58593394,  3.58593394,  3.58593394])

### refrence

https://cs231n.github.io/python-numpy-tutorial/

http://index-of.es/Varios-2/NumPy%20Tutorial.pdf

https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf

https://numpy.org/doc/1.20/numpy-user.pdf

SVD

In [76]:
a = np.random.randn(9, 6) 
# + 1j*np.random.randn(9, 6)

In [77]:
a

array([[ 0.85226679,  0.73636951,  0.42285109, -1.06770864, -1.46757496,
        -0.15953128],
       [-0.38814395, -0.69886725,  1.29013953, -2.23441001, -0.60674059,
         0.18460541],
       [-0.2594574 , -0.73912896,  0.44397481, -0.62200557, -1.29437191,
         0.92086681],
       [-0.38758635,  0.04387621, -1.33872667, -0.57991243, -0.4907336 ,
        -0.1590867 ],
       [ 0.12922004, -0.64476756, -1.88567088,  0.59718227,  0.77863206,
         1.21286751],
       [ 0.34062517, -0.51452008,  0.81864212, -0.05249653, -0.45944293,
         0.6874794 ],
       [ 1.30761618, -0.43583305,  0.33642198, -0.45656615,  0.90704251,
         0.27963622],
       [ 1.01577018,  1.30510026,  1.12092615,  1.43920984, -1.73796349,
         0.29907592],
       [ 0.09234666,  1.08145036, -0.39757339, -0.34505051, -0.2608793 ,
         1.0131411 ]])

In [70]:
u, s, vh = np.linalg.svd(a, full_matrices=True)

In [71]:
u

array([[-0.17868047, -0.67665344, -0.30161565, -0.23187547, -0.04848246,
        -0.46403355, -0.22991867, -0.02879071,  0.306767  ],
       [ 0.48273844,  0.3952051 , -0.05480088, -0.04248414, -0.09263556,
        -0.66277448, -0.04704431,  0.39151258,  0.05120418],
       [-0.36262359,  0.243869  , -0.68931086,  0.22364208, -0.21847039,
        -0.18207051,  0.15466982, -0.16143581, -0.39115668],
       [ 0.06169307,  0.01512845,  0.41344854, -0.03279423, -0.36510694,
        -0.36281792,  0.25232776, -0.70305979, -0.03236741],
       [-0.35920582, -0.26176768,  0.41457433,  0.04242505, -0.32898521,
        -0.14202993,  0.16706441,  0.52897438, -0.43891789],
       [-0.55626384,  0.41952147,  0.17939101, -0.53738643,  0.35833038,
        -0.20126281, -0.15022076, -0.04567578,  0.00685867],
       [ 0.04627696, -0.12399851, -0.12207395, -0.19322888,  0.3387255 ,
        -0.05661077,  0.88592084,  0.10394517,  0.12900887],
       [ 0.04320503,  0.14195211, -0.17399686, -0.58517474, -0

In [72]:
s

array([4.09074226, 3.11129083, 2.22254846, 1.69745776, 0.92078278,
       0.55394863])

In [73]:
vh

array([[ 0.43793699,  0.05598857, -0.0329122 , -0.67884105, -0.47249855,
         0.34628486],
       [ 0.64621968,  0.14566503, -0.41116937,  0.26646741, -0.14034681,
        -0.54901682],
       [ 0.06621705,  0.93014316,  0.23798074, -0.0446764 ,  0.26165381,
         0.05792648],
       [-0.55192713,  0.19180887, -0.12725264, -0.38987026, -0.36003303,
        -0.6006413 ],
       [ 0.24253995, -0.26163836,  0.28992293, -0.50741308,  0.60751644,
        -0.40264149],
       [-0.15092197,  0.07235613, -0.82034942, -0.23813253,  0.43575815,
         0.2289579 ]])