<h1>1) Reinfrcement Learning_ The K_armed bandit problem</h1>

In [92]:
import numpy as np
import random

In [93]:
class BernulliBandit:
    def __init__(self, p, verbose=True):
        self.p = p
        
        if verbose:
            print("Creating Be.Ban with p =", p)
    def pull(self):
        return np.random.binomial(1, self.p)

In [94]:
BB = BernulliBandit(0.7)
BB.pull()

Creating Be.Ban with p = 0.7


1

In [95]:
class BanditGame():
    def __init__(self, K, T, verbose=True):
        self.K = K
        self.T=T
        self.Bandits = [BernulliBandit(np.random.uniform(), verbose) for i in range(K)]
        self.verbose = verbose
        
    def run_Stochastic(self):
        results = np.zeros(self.T)
        for t in range(self.T):
            k=random.randrange(self.K)
            results[t]= self.Bandits[k].pull()
            if self.verbose:
                print("T=", t, "playing bandit", k, "reward is ", results[t])
                
        return results

In [96]:
BG = BanditGame(5,10)
BG.run_Stochastic()

Creating Be.Ban with p = 0.19195169860236294
Creating Be.Ban with p = 0.7119691369333576
Creating Be.Ban with p = 0.6615951670733868
Creating Be.Ban with p = 0.30558062323464663
Creating Be.Ban with p = 0.0007318846623753927
T= 0 playing bandit 3 reward is  0.0
T= 1 playing bandit 0 reward is  0.0
T= 2 playing bandit 0 reward is  1.0
T= 3 playing bandit 4 reward is  0.0
T= 4 playing bandit 2 reward is  1.0
T= 5 playing bandit 4 reward is  0.0
T= 6 playing bandit 1 reward is  1.0
T= 7 playing bandit 4 reward is  0.0
T= 8 playing bandit 4 reward is  0.0
T= 9 playing bandit 2 reward is  1.0


array([0., 0., 1., 0., 1., 0., 1., 0., 0., 1.])

In [97]:
def run_simulation(n_runs, runs_per_game , K , T):
    results = np.zeros((K,T))
    for run in range(n_runs):
        run_results = np.zeros((K,T))
        
        for run in range(runs_per_game):
            BG = BanditGame(K,T,verbose=False)
            run_results += BG.run_Stochastic()
            print(run_results)
            
        results += run_results / runs_per_game
        print(results)
        
    results = results / n_runs
    return results

In [103]:
RS = run_simulation(10,100,3,1000)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
[[0. 2. 1. ... 0. 0. 0.]
 [0. 2. 1. ... 0. 0. 0.]
 [0. 2. 1. ... 0. 0. 0.]]
[[0. 2. 2. ... 0. 1. 0.]
 [0. 2. 2. ... 0. 1. 0.]
 [0. 2. 2. ... 0. 1. 0.]]
[[0. 2. 3. ... 1. 2. 1.]
 [0. 2. 3. ... 1. 2. 1.]
 [0. 2. 3. ... 1. 2. 1.]]
[[0. 3. 3. ... 2. 2. 1.]
 [0. 3. 3. ... 2. 2. 1.]
 [0. 3. 3. ... 2. 2. 1.]]
[[1. 4. 3. ... 2. 3. 1.]
 [1. 4. 3. ... 2. 3. 1.]
 [1. 4. 3. ... 2. 3. 1.]]
[[2. 5. 4. ... 2. 3. 2.]
 [2. 5. 4. ... 2. 3. 2.]
 [2. 5. 4. ... 2. 3. 2.]]
[[3. 5. 5. ... 3. 3. 2.]
 [3. 5. 5. ... 3. 3. 2.]
 [3. 5. 5. ... 3. 3. 2.]]
[[3. 6. 6. ... 3. 4. 3.]
 [3. 6. 6. ... 3. 4. 3.]
 [3. 6. 6. ... 3. 4. 3.]]
[[3. 6. 6. ... 3. 4. 3.]
 [3. 6. 6. ... 3. 4. 3.]
 [3. 6. 6. ... 3. 4. 3.]]
[[3. 7. 6. ... 4. 4. 3.]
 [3. 7. 6. ... 4. 4. 3.]
 [3. 7. 6. ... 4. 4. 3.]]
[[3. 8. 6. ... 5. 4. 3.]
 [3. 8. 6. ... 5. 4. 3.]
 [3. 8. 6. ... 5. 4. 3.]]
[[3. 9. 7. ... 5. 4. 3.]
 [3. 9. 7. ... 5. 4. 3.]
 [3. 9. 7. ... 5. 4. 3.]]
[[ 4. 10.  7

[[40. 50. 39. ... 34. 42. 37.]
 [40. 50. 39. ... 34. 42. 37.]
 [40. 50. 39. ... 34. 42. 37.]]
[[40. 50. 40. ... 34. 43. 38.]
 [40. 50. 40. ... 34. 43. 38.]
 [40. 50. 40. ... 34. 43. 38.]]
[[40. 51. 40. ... 34. 44. 39.]
 [40. 51. 40. ... 34. 44. 39.]
 [40. 51. 40. ... 34. 44. 39.]]
[[41. 51. 40. ... 35. 45. 39.]
 [41. 51. 40. ... 35. 45. 39.]
 [41. 51. 40. ... 35. 45. 39.]]
[[42. 52. 41. ... 36. 46. 39.]
 [42. 52. 41. ... 36. 46. 39.]
 [42. 52. 41. ... 36. 46. 39.]]
[[43. 53. 41. ... 37. 47. 39.]
 [43. 53. 41. ... 37. 47. 39.]
 [43. 53. 41. ... 37. 47. 39.]]
[[44. 53. 41. ... 38. 48. 40.]
 [44. 53. 41. ... 38. 48. 40.]
 [44. 53. 41. ... 38. 48. 40.]]
[[44. 53. 42. ... 38. 49. 41.]
 [44. 53. 42. ... 38. 49. 41.]
 [44. 53. 42. ... 38. 49. 41.]]
[[0.44 0.53 0.42 ... 0.38 0.49 0.41]
 [0.44 0.53 0.42 ... 0.38 0.49 0.41]
 [0.44 0.53 0.42 ... 0.38 0.49 0.41]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0.

[[41. 41. 44. ... 32. 41. 40.]
 [41. 41. 44. ... 32. 41. 40.]
 [41. 41. 44. ... 32. 41. 40.]]
[[42. 42. 45. ... 33. 41. 41.]
 [42. 42. 45. ... 33. 41. 41.]
 [42. 42. 45. ... 33. 41. 41.]]
[[43. 43. 46. ... 34. 42. 42.]
 [43. 43. 46. ... 34. 42. 42.]
 [43. 43. 46. ... 34. 42. 42.]]
[[43. 44. 46. ... 35. 42. 43.]
 [43. 44. 46. ... 35. 42. 43.]
 [43. 44. 46. ... 35. 42. 43.]]
[[44. 45. 46. ... 35. 43. 44.]
 [44. 45. 46. ... 35. 43. 44.]
 [44. 45. 46. ... 35. 43. 44.]]
[[44. 45. 47. ... 36. 43. 45.]
 [44. 45. 47. ... 36. 43. 45.]
 [44. 45. 47. ... 36. 43. 45.]]
[[45. 45. 48. ... 37. 43. 46.]
 [45. 45. 48. ... 37. 43. 46.]
 [45. 45. 48. ... 37. 43. 46.]]
[[46. 46. 49. ... 37. 44. 47.]
 [46. 46. 49. ... 37. 44. 47.]
 [46. 46. 49. ... 37. 44. 47.]]
[[47. 46. 49. ... 38. 44. 48.]
 [47. 46. 49. ... 38. 44. 48.]
 [47. 46. 49. ... 38. 44. 48.]]
[[47. 47. 49. ... 38. 45. 49.]
 [47. 47. 49. ... 38. 45. 49.]
 [47. 47. 49. ... 38. 45. 49.]]
[[47. 47. 50. ... 38. 45. 49.]
 [47. 47. 50. ... 38. 45. 49.

[[33. 36. 37. ... 41. 35. 30.]
 [33. 36. 37. ... 41. 35. 30.]
 [33. 36. 37. ... 41. 35. 30.]]
[[34. 37. 38. ... 42. 36. 31.]
 [34. 37. 38. ... 42. 36. 31.]
 [34. 37. 38. ... 42. 36. 31.]]
[[35. 38. 38. ... 43. 37. 31.]
 [35. 38. 38. ... 43. 37. 31.]
 [35. 38. 38. ... 43. 37. 31.]]
[[35. 39. 39. ... 43. 38. 32.]
 [35. 39. 39. ... 43. 38. 32.]
 [35. 39. 39. ... 43. 38. 32.]]
[[36. 39. 39. ... 44. 38. 33.]
 [36. 39. 39. ... 44. 38. 33.]
 [36. 39. 39. ... 44. 38. 33.]]
[[37. 39. 40. ... 45. 38. 34.]
 [37. 39. 40. ... 45. 38. 34.]
 [37. 39. 40. ... 45. 38. 34.]]
[[37. 39. 41. ... 45. 39. 35.]
 [37. 39. 41. ... 45. 39. 35.]
 [37. 39. 41. ... 45. 39. 35.]]
[[37. 39. 41. ... 45. 39. 36.]
 [37. 39. 41. ... 45. 39. 36.]
 [37. 39. 41. ... 45. 39. 36.]]
[[38. 39. 41. ... 45. 39. 36.]
 [38. 39. 41. ... 45. 39. 36.]
 [38. 39. 41. ... 45. 39. 36.]]
[[38. 40. 42. ... 46. 39. 37.]
 [38. 40. 42. ... 46. 39. 37.]
 [38. 40. 42. ... 46. 39. 37.]]
[[38. 40. 43. ... 46. 39. 38.]
 [38. 40. 43. ... 46. 39. 38.

[[37. 32. 36. ... 42. 48. 43.]
 [37. 32. 36. ... 42. 48. 43.]
 [37. 32. 36. ... 42. 48. 43.]]
[[37. 32. 37. ... 43. 49. 43.]
 [37. 32. 37. ... 43. 49. 43.]
 [37. 32. 37. ... 43. 49. 43.]]
[[38. 33. 37. ... 44. 49. 43.]
 [38. 33. 37. ... 44. 49. 43.]
 [38. 33. 37. ... 44. 49. 43.]]
[[38. 33. 38. ... 44. 49. 43.]
 [38. 33. 38. ... 44. 49. 43.]
 [38. 33. 38. ... 44. 49. 43.]]
[[39. 33. 39. ... 44. 49. 43.]
 [39. 33. 39. ... 44. 49. 43.]
 [39. 33. 39. ... 44. 49. 43.]]
[[40. 34. 40. ... 44. 50. 43.]
 [40. 34. 40. ... 44. 50. 43.]
 [40. 34. 40. ... 44. 50. 43.]]
[[41. 35. 41. ... 45. 51. 44.]
 [41. 35. 41. ... 45. 51. 44.]
 [41. 35. 41. ... 45. 51. 44.]]
[[42. 36. 42. ... 46. 52. 44.]
 [42. 36. 42. ... 46. 52. 44.]
 [42. 36. 42. ... 46. 52. 44.]]
[[43. 37. 42. ... 47. 52. 45.]
 [43. 37. 42. ... 47. 52. 45.]
 [43. 37. 42. ... 47. 52. 45.]]
[[44. 38. 43. ... 47. 52. 46.]
 [44. 38. 43. ... 47. 52. 46.]
 [44. 38. 43. ... 47. 52. 46.]]
[[44. 39. 43. ... 47. 52. 47.]
 [44. 39. 43. ... 47. 52. 47.

[[30. 36. 39. ... 41. 37. 36.]
 [30. 36. 39. ... 41. 37. 36.]
 [30. 36. 39. ... 41. 37. 36.]]
[[31. 37. 39. ... 42. 38. 37.]
 [31. 37. 39. ... 42. 38. 37.]
 [31. 37. 39. ... 42. 38. 37.]]
[[32. 38. 39. ... 43. 39. 38.]
 [32. 38. 39. ... 43. 39. 38.]
 [32. 38. 39. ... 43. 39. 38.]]
[[32. 38. 39. ... 44. 39. 38.]
 [32. 38. 39. ... 44. 39. 38.]
 [32. 38. 39. ... 44. 39. 38.]]
[[32. 38. 39. ... 44. 39. 39.]
 [32. 38. 39. ... 44. 39. 39.]
 [32. 38. 39. ... 44. 39. 39.]]
[[32. 38. 39. ... 44. 40. 40.]
 [32. 38. 39. ... 44. 40. 40.]
 [32. 38. 39. ... 44. 40. 40.]]
[[33. 39. 40. ... 45. 41. 41.]
 [33. 39. 40. ... 45. 41. 41.]
 [33. 39. 40. ... 45. 41. 41.]]
[[34. 40. 40. ... 46. 42. 41.]
 [34. 40. 40. ... 46. 42. 41.]
 [34. 40. 40. ... 46. 42. 41.]]
[[35. 41. 40. ... 46. 42. 42.]
 [35. 41. 40. ... 46. 42. 42.]
 [35. 41. 40. ... 46. 42. 42.]]
[[36. 42. 40. ... 46. 43. 43.]
 [36. 42. 40. ... 46. 43. 43.]
 [36. 42. 40. ... 46. 43. 43.]]
[[37. 43. 40. ... 47. 44. 43.]
 [37. 43. 40. ... 47. 44. 43.

[[39. 42. 38. ... 40. 33. 38.]
 [39. 42. 38. ... 40. 33. 38.]
 [39. 42. 38. ... 40. 33. 38.]]
[[39. 43. 38. ... 41. 33. 38.]
 [39. 43. 38. ... 41. 33. 38.]
 [39. 43. 38. ... 41. 33. 38.]]
[[39. 44. 39. ... 41. 34. 39.]
 [39. 44. 39. ... 41. 34. 39.]
 [39. 44. 39. ... 41. 34. 39.]]
[[39. 44. 40. ... 41. 35. 39.]
 [39. 44. 40. ... 41. 35. 39.]
 [39. 44. 40. ... 41. 35. 39.]]
[[39. 44. 40. ... 41. 35. 39.]
 [39. 44. 40. ... 41. 35. 39.]
 [39. 44. 40. ... 41. 35. 39.]]
[[39. 45. 40. ... 42. 36. 40.]
 [39. 45. 40. ... 42. 36. 40.]
 [39. 45. 40. ... 42. 36. 40.]]
[[40. 45. 41. ... 43. 36. 41.]
 [40. 45. 41. ... 43. 36. 41.]
 [40. 45. 41. ... 43. 36. 41.]]
[[41. 46. 42. ... 44. 36. 42.]
 [41. 46. 42. ... 44. 36. 42.]
 [41. 46. 42. ... 44. 36. 42.]]
[[41. 46. 42. ... 44. 37. 43.]
 [41. 46. 42. ... 44. 37. 43.]
 [41. 46. 42. ... 44. 37. 43.]]
[[42. 47. 42. ... 45. 37. 43.]
 [42. 47. 42. ... 45. 37. 43.]
 [42. 47. 42. ... 45. 37. 43.]]
[[42. 48. 42. ... 46. 37. 43.]
 [42. 48. 42. ... 46. 37. 43.

[[37. 31. 33. ... 27. 36. 33.]
 [37. 31. 33. ... 27. 36. 33.]
 [37. 31. 33. ... 27. 36. 33.]]
[[38. 31. 34. ... 27. 36. 34.]
 [38. 31. 34. ... 27. 36. 34.]
 [38. 31. 34. ... 27. 36. 34.]]
[[39. 32. 34. ... 27. 37. 35.]
 [39. 32. 34. ... 27. 37. 35.]
 [39. 32. 34. ... 27. 37. 35.]]
[[40. 33. 35. ... 28. 37. 36.]
 [40. 33. 35. ... 28. 37. 36.]
 [40. 33. 35. ... 28. 37. 36.]]
[[41. 33. 35. ... 29. 38. 37.]
 [41. 33. 35. ... 29. 38. 37.]
 [41. 33. 35. ... 29. 38. 37.]]
[[42. 34. 35. ... 30. 39. 37.]
 [42. 34. 35. ... 30. 39. 37.]
 [42. 34. 35. ... 30. 39. 37.]]
[[42. 35. 35. ... 30. 39. 38.]
 [42. 35. 35. ... 30. 39. 38.]
 [42. 35. 35. ... 30. 39. 38.]]
[[42. 35. 36. ... 31. 40. 38.]
 [42. 35. 36. ... 31. 40. 38.]
 [42. 35. 36. ... 31. 40. 38.]]
[[42. 36. 36. ... 31. 40. 38.]
 [42. 36. 36. ... 31. 40. 38.]
 [42. 36. 36. ... 31. 40. 38.]]
[[43. 36. 37. ... 32. 41. 38.]
 [43. 36. 37. ... 32. 41. 38.]
 [43. 36. 37. ... 32. 41. 38.]]
[[44. 36. 37. ... 33. 41. 39.]
 [44. 36. 37. ... 33. 41. 39.

[[20. 35. 28. ... 26. 26. 26.]
 [20. 35. 28. ... 26. 26. 26.]
 [20. 35. 28. ... 26. 26. 26.]]
[[20. 35. 29. ... 26. 26. 27.]
 [20. 35. 29. ... 26. 26. 27.]
 [20. 35. 29. ... 26. 26. 27.]]
[[21. 36. 30. ... 27. 27. 28.]
 [21. 36. 30. ... 27. 27. 28.]
 [21. 36. 30. ... 27. 27. 28.]]
[[21. 37. 30. ... 27. 28. 29.]
 [21. 37. 30. ... 27. 28. 29.]
 [21. 37. 30. ... 27. 28. 29.]]
[[22. 37. 31. ... 27. 29. 29.]
 [22. 37. 31. ... 27. 29. 29.]
 [22. 37. 31. ... 27. 29. 29.]]
[[22. 37. 31. ... 27. 29. 30.]
 [22. 37. 31. ... 27. 29. 30.]
 [22. 37. 31. ... 27. 29. 30.]]
[[23. 37. 31. ... 28. 30. 30.]
 [23. 37. 31. ... 28. 30. 30.]
 [23. 37. 31. ... 28. 30. 30.]]
[[23. 37. 32. ... 28. 30. 30.]
 [23. 37. 32. ... 28. 30. 30.]
 [23. 37. 32. ... 28. 30. 30.]]
[[23. 37. 32. ... 28. 30. 30.]
 [23. 37. 32. ... 28. 30. 30.]
 [23. 37. 32. ... 28. 30. 30.]]
[[23. 37. 33. ... 28. 30. 30.]
 [23. 37. 33. ... 28. 30. 30.]
 [23. 37. 33. ... 28. 30. 30.]]
[[23. 38. 34. ... 29. 31. 31.]
 [23. 38. 34. ... 29. 31. 31.

 [31. 25. 23. ... 22. 25. 21.]]
[[31. 25. 24. ... 23. 25. 21.]
 [31. 25. 24. ... 23. 25. 21.]
 [31. 25. 24. ... 23. 25. 21.]]
[[31. 26. 24. ... 24. 26. 21.]
 [31. 26. 24. ... 24. 26. 21.]
 [31. 26. 24. ... 24. 26. 21.]]
[[32. 26. 24. ... 24. 26. 21.]
 [32. 26. 24. ... 24. 26. 21.]
 [32. 26. 24. ... 24. 26. 21.]]
[[33. 26. 25. ... 25. 27. 22.]
 [33. 26. 25. ... 25. 27. 22.]
 [33. 26. 25. ... 25. 27. 22.]]
[[34. 27. 26. ... 26. 28. 22.]
 [34. 27. 26. ... 26. 28. 22.]
 [34. 27. 26. ... 26. 28. 22.]]
[[35. 28. 27. ... 27. 29. 22.]
 [35. 28. 27. ... 27. 29. 22.]
 [35. 28. 27. ... 27. 29. 22.]]
[[36. 28. 27. ... 28. 29. 23.]
 [36. 28. 27. ... 28. 29. 23.]
 [36. 28. 27. ... 28. 29. 23.]]
[[37. 29. 27. ... 29. 30. 24.]
 [37. 29. 27. ... 29. 30. 24.]
 [37. 29. 27. ... 29. 30. 24.]]
[[38. 29. 28. ... 29. 30. 25.]
 [38. 29. 28. ... 29. 30. 25.]
 [38. 29. 28. ... 29. 30. 25.]]
[[39. 30. 28. ... 30. 31. 26.]
 [39. 30. 28. ... 30. 31. 26.]
 [39. 30. 28. ... 30. 31. 26.]]
[[39. 31. 28. ... 30. 31. 26

[[20. 19. 27. ... 16. 22. 23.]
 [20. 19. 27. ... 16. 22. 23.]
 [20. 19. 27. ... 16. 22. 23.]]
[[21. 20. 28. ... 16. 23. 24.]
 [21. 20. 28. ... 16. 23. 24.]
 [21. 20. 28. ... 16. 23. 24.]]
[[22. 21. 28. ... 16. 24. 25.]
 [22. 21. 28. ... 16. 24. 25.]
 [22. 21. 28. ... 16. 24. 25.]]
[[22. 21. 28. ... 16. 24. 26.]
 [22. 21. 28. ... 16. 24. 26.]
 [22. 21. 28. ... 16. 24. 26.]]
[[23. 21. 29. ... 17. 25. 27.]
 [23. 21. 29. ... 17. 25. 27.]
 [23. 21. 29. ... 17. 25. 27.]]
[[24. 22. 29. ... 17. 25. 28.]
 [24. 22. 29. ... 17. 25. 28.]
 [24. 22. 29. ... 17. 25. 28.]]
[[24. 22. 30. ... 18. 25. 28.]
 [24. 22. 30. ... 18. 25. 28.]
 [24. 22. 30. ... 18. 25. 28.]]
[[25. 22. 30. ... 19. 26. 29.]
 [25. 22. 30. ... 19. 26. 29.]
 [25. 22. 30. ... 19. 26. 29.]]
[[25. 22. 31. ... 20. 27. 29.]
 [25. 22. 31. ... 20. 27. 29.]
 [25. 22. 31. ... 20. 27. 29.]]
[[25. 23. 32. ... 20. 27. 29.]
 [25. 23. 32. ... 20. 27. 29.]
 [25. 23. 32. ... 20. 27. 29.]]
[[26. 23. 33. ... 20. 28. 29.]
 [26. 23. 33. ... 20. 28. 29.

In [104]:
s=np.zeros((4,4))
s+=[1,2,3,5]
s

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [105]:
mean_reward = RS.mean(axis=0)
mean_reward

array([0.479, 0.511, 0.493, 0.516, 0.494, 0.473, 0.475, 0.464, 0.482,
       0.497, 0.497, 0.507, 0.512, 0.505, 0.48 , 0.501, 0.492, 0.485,
       0.511, 0.492, 0.508, 0.464, 0.474, 0.488, 0.507, 0.519, 0.502,
       0.493, 0.509, 0.476, 0.471, 0.507, 0.492, 0.506, 0.474, 0.495,
       0.491, 0.496, 0.497, 0.495, 0.52 , 0.481, 0.459, 0.51 , 0.489,
       0.481, 0.501, 0.486, 0.493, 0.473, 0.528, 0.477, 0.475, 0.5  ,
       0.479, 0.504, 0.529, 0.495, 0.485, 0.472, 0.475, 0.514, 0.521,
       0.487, 0.495, 0.483, 0.497, 0.513, 0.499, 0.499, 0.492, 0.513,
       0.474, 0.469, 0.531, 0.501, 0.477, 0.457, 0.472, 0.505, 0.485,
       0.487, 0.494, 0.496, 0.5  , 0.487, 0.493, 0.502, 0.478, 0.506,
       0.506, 0.481, 0.512, 0.5  , 0.489, 0.508, 0.503, 0.502, 0.465,
       0.479, 0.486, 0.49 , 0.486, 0.471, 0.5  , 0.511, 0.474, 0.486,
       0.492, 0.488, 0.48 , 0.506, 0.498, 0.459, 0.516, 0.488, 0.485,
       0.497, 0.48 , 0.491, 0.503, 0.48 , 0.481, 0.491, 0.471, 0.478,
       0.5  , 0.5  ,

In [106]:
print("s= \n",s)
s.mean(axis=0)

s= 
 [[1. 2. 3. 5.]
 [1. 2. 3. 5.]
 [1. 2. 3. 5.]
 [1. 2. 3. 5.]]


array([1., 2., 3., 5.])

In [107]:
print("Mean reward: ", mean_reward.mean())
print("Sum of All results: ", mean_reward.sum())

Mean reward:  0.49285
Sum of All results:  492.85
